// Banco de preguntas para el modo Trivia (generado + verificado).
// Cada entrada: { id, clue, answers[] } — respuestas en MAYUS, en el diccionario y colocables.
window.TYPO_TRIVIA = [
  { id: "cantar", clue: "Acción de emitir sonidos musicales con la voz", answers: ["CANTA","CANTABA","CANTABAN","CANTABAS","CANTADA","CANTADO","CANTAMOS","CANTAN","CANTAR","CANTARON","CANTAS","CANTASTE","CANTE","CANTEMOS","CANTEN","CANTES","CANTO"] },
  { id: "bailar", clue: "Mover el cuerpo al ritmo de la música", answers: ["BAILA","BAILABA","BAILABAN","BAILABAS","BAILADA","BAILADO","BAILAMOS","BAILAN","BAILAR","BAILARON","BAILAS","BAILASTE","BAILE","BAILEMOS","BAILEN","BAILES","BAILO"] },
  { id: "saltar", clue: "Elevarse del suelo con impulso", answers: ["SALTA","SALTABA","SALTABAN","SALTABAS","SALTADA","SALTADO","SALTAMOS","SALTAN","SALTAR","SALTARON","SALTAS","SALTASTE","SALTE","SALTEMOS","SALTEN","SALTES","SALTO"] },
  { id: "mirar", clue: "Fijar la vista en algo", answers: ["MIRA","MIRABA","MIRABAN","MIRABAS","MIRADA","MIRADO","MIRAMOS","MIRAN","MIRAR","MIRARON","MIRAS","MIRASTE","MIRE","MIREMOS","MIREN","MIRES","MIRO"] },
  { id: "tomar", clue: "Coger o agarrar algo", answers: ["TOMA","TOMABA","TOMABAN","TOMABAS","TOMADA","TOMADO","TOMAMOS","TOMAN","TOMAR","TOMARON","TOMAS","TOMASTE","TOME","TOMEMOS","TOMEN","TOMES","TOMO"] },
  { id: "amar", clue: "Sentir amor por alguien", answers: ["AMA","AMABA","AMABAN","AMABAS","AMADA","AMADO","AMAMOS","AMAN","AMAR","AMARON","AMAS","AMASTE","AME","AMEMOS","AMEN","AMES","AMO"] },
  { id: "pasar", clue: "Ir de un lugar a otro", answers: ["PASA","PASABA","PASABAN","PASABAS","PASADA","PASADO","PASAMOS","PASAN","PASAR","PASARON","PASAS","PASASTE","PASE","PASEMOS","PASEN","PASES","PASO"] },
  { id: "llorar", clue: "Derramar lágrimas", answers: ["LLORA","LLORABA","LLORABAN","LLORABAS","LLORADA","LLORADO","LLORAMOS","LLORAN","LLORAR","LLORARON","LLORAS","LLORASTE","LLORE","LLOREMOS","LLOREN","LLORES","LLORO"] },
  { id: "ganar", clue: "Obtener una victoria o premio", answers: ["GANA","GANABA","GANABAN","GANABAS","GANADA","GANADO","GANAMOS","GANAN","GANAR","GANARON","GANAS","GANASTE","GANE","GANEMOS","GANEN","GANES","GANO"] },
  { id: "pagar", clue: "Dar dinero por algo", answers: ["PAGA","PAGABA","PAGABAN","PAGABAS","PAGADA","PAGADO","PAGAMOS","PAGAN","PAGAR","PAGARON","PAGAS","PAGASTE","PAGO"] },
  { id: "lavar", clue: "Limpiar con agua", answers: ["LAVA","LAVABA","LAVABAN","LAVABAS","LAVADA","LAVADO","LAVAMOS","LAVAN","LAVAR","LAVARON","LAVAS","LAVASTE","LAVE","LAVEMOS","LAVEN","LAVES","LAVO"] },
  { id: "cortar", clue: "Dividir con un filo", answers: ["CORTA","CORTABA","CORTABAN","CORTABAS","CORTADA","CORTADO","CORTAMOS","CORTAN","CORTAR","CORTARON","CORTAS","CORTASTE","CORTE","CORTEMOS","CORTEN","CORTES","CORTO"] },
  { id: "pintar", clue: "Cubrir con color", answers: ["PINTA","PINTABA","PINTABAN","PINTABAS","PINTADA","PINTADO","PINTAMOS","PINTAN","PINTAR","PINTARON","PINTAS","PINTASTE","PINTE","PINTEMOS","PINTEN","PINTES","PINTO"] },
  { id: "nadar", clue: "Desplazarse en el agua", answers: ["NADA","NADABA","NADABAN","NADABAS","NADADO","NADAMOS","NADAN","NADAR","NADARON","NADAS","NADASTE","NADE","NADEMOS","NADEN","NADES","NADO"] },
  { id: "gritar", clue: "Alzar mucho la voz", answers: ["GRITA","GRITABA","GRITABAN","GRITABAS","GRITADA","GRITADO","GRITAMOS","GRITAN","GRITAR","GRITARON","GRITAS","GRITASTE","GRITE","GRITEMOS","GRITEN","GRITES","GRITO"] },
  { id: "besar", clue: "Tocar con los labios en señal de cariño", answers: ["BESA","BESABA","BESABAN","BESABAS","BESADA","BESADO","BESAMOS","BESAN","BESAR","BESARON","BESAS","BESASTE","BESE","BESEMOS","BESEN","BESES","BESO"] },
  { id: "robar", clue: "Quitar algo ajeno", answers: ["ROBA","ROBABA","ROBABAN","ROBABAS","ROBADA","ROBADO","ROBAMOS","ROBAN","ROBAR","ROBARON","ROBAS","ROBASTE","ROBE","ROBEMOS","ROBEN","ROBES","ROBO"] },
  { id: "curar", clue: "Sanar a un enfermo", answers: ["CURA","CURABA","CURABAN","CURABAS","CURADA","CURADO","CURAMOS","CURAN","CURAR","CURARON","CURAS","CURASTE","CURE","CUREMOS","CUREN","CURES","CURO"] },
  { id: "tirar", clue: "Lanzar o arrojar algo", answers: ["TIRA","TIRABA","TIRABAN","TIRABAS","TIRADA","TIRADO","TIRAMOS","TIRAN","TIRAR","TIRARON","TIRAS","TIRASTE","TIRE","TIREMOS","TIREN","TIRES","TIRO"] },
  { id: "secar", clue: "Quitar la humedad", answers: ["SECA","SECABA","SECABAN","SECABAS","SECADA","SECADO","SECAMOS","SECAN","SECAR","SECARON","SECAS","SECASTE","SECE","SECO"] },
  { id: "mojar", clue: "Humedecer con líquido", answers: ["MOJA","MOJABA","MOJABAN","MOJABAS","MOJADA","MOJADO","MOJAMOS","MOJAN","MOJAR","MOJARON","MOJAS","MOJASTE","MOJE","MOJEMOS","MOJEN","MOJES","MOJO"] },
  { id: "entrar", clue: "Pasar de fuera a dentro", answers: ["ENTRA","ENTRABA","ENTRABAN","ENTRABAS","ENTRADA","ENTRADO","ENTRAMOS","ENTRAN","ENTRAR","ENTRARON","ENTRAS","ENTRASTE","ENTRE","ENTREMOS","ENTREN","ENTRES","ENTRO"] },
  { id: "hablar", clue: "Comunicarse con palabras", answers: ["HABLA","HABLABA","HABLABAN","HABLABAS","HABLADA","HABLADO","HABLAMOS","HABLAN","HABLAR","HABLARON","HABLAS","HABLASTE","HABLE","HABLEMOS","HABLEN","HABLES","HABLO"] },
  { id: "caminar", clue: "Andar dando pasos", answers: ["CAMINA","CAMINABA","CAMINABAN","CAMINABAS","CAMINADA","CAMINADO","CAMINAMOS","CAMINAN","CAMINAR","CAMINARON","CAMINAS","CAMINASTE","CAMINE","CAMINEMOS","CAMINEN","CAMINES","CAMINO"] },
  { id: "comprar", clue: "Adquirir algo con dinero", answers: ["COMPRA","COMPRABA","COMPRABAN","COMPRABAS","COMPRADA","COMPRADO","COMPRAMOS","COMPRAN","COMPRAR","COMPRARON","COMPRAS","COMPRASTE","COMPRE","COMPREMOS","COMPREN","COMPRES","COMPRO"] },
  { id: "ayudar", clue: "Prestar auxilio a alguien", answers: ["AYUDA","AYUDABA","AYUDABAN","AYUDABAS","AYUDADA","AYUDADO","AYUDAMOS","AYUDAN","AYUDAR","AYUDARON","AYUDAS","AYUDASTE","AYUDE","AYUDEMOS","AYUDEN","AYUDES","AYUDO"] },
  { id: "patear", clue: "Golpear con el pie", answers: ["PATEA","PATEABA","PATEABAN","PATEABAS","PATEADA","PATEADO","PATEAMOS","PATEAN","PATEAR","PATEARON","PATEAS","PATEASTE","PATEE","PATEEMOS","PATEEN","PATEES","PATEO"] },
  { id: "sumar", clue: "Añadir cantidades", answers: ["SUMA","SUMABA","SUMABAN","SUMABAS","SUMADA","SUMADO","SUMAMOS","SUMAN","SUMAR","SUMARON","SUMAS","SUMASTE","SUME","SUMEMOS","SUMEN","SUMES","SUMO"] },
  { id: "restar", clue: "Quitar una cantidad de otra", answers: ["RESTA","RESTABA","RESTABAN","RESTABAS","RESTADA","RESTADO","RESTAMOS","RESTAN","RESTAR","RESTARON","RESTAS","RESTASTE","RESTE","RESTEMOS","RESTEN","RESTES","RESTO"] },
  { id: "pescar", clue: "Sacar peces del agua", answers: ["PESCA","PESCABA","PESCABAN","PESCABAS","PESCADA","PESCADO","PESCAMOS","PESCAN","PESCAR","PESCARON","PESCAS","PESCASTE","PESCE","PESCO"] },
  { id: "cazar", clue: "Perseguir animales para atraparlos", answers: ["CAZA","CAZABA","CAZABAN","CAZABAS","CAZADA","CAZADO","CAZAMOS","CAZAN","CAZAR","CAZARON","CAZAS","CAZASTE","CAZO"] },
  { id: "brincar", clue: "Dar saltos", answers: ["BRINCA","BRINCABA","BRINCABAN","BRINCABAS","BRINCADA","BRINCADO","BRINCAMOS","BRINCAN","BRINCAR","BRINCARON","BRINCAS","BRINCASTE","BRINCO"] },
  { id: "rezar", clue: "Dirigir una oración", answers: ["REZA","REZABA","REZABAN","REZABAS","REZADA","REZADO","REZAMOS","REZAN","REZAR","REZARON","REZAS","REZASTE","REZO"] },
  { id: "pesar", clue: "Determinar el peso", answers: ["PESA","PESABA","PESABAN","PESABAS","PESADA","PESADO","PESAMOS","PESAN","PESAR","PESARON","PESAS","PESASTE","PESE","PESEMOS","PESEN","PESES","PESO"] },
  { id: "cargar", clue: "Llevar un peso", answers: ["CARGA","CARGABA","CARGABAN","CARGABAS","CARGADA","CARGADO","CARGAMOS","CARGAN","CARGAR","CARGARON","CARGAS","CARGASTE","CARGO"] },
  { id: "comer", clue: "Ingerir alimento", answers: ["COMA","COMAN","COMAS","COME","COMEMOS","COMEN","COMER","COMES","COMI","COMIA","COMIAN","COMIDA","COMIDO","COMIERON","COMIO","COMISTE","COMO"] },
  { id: "correr", clue: "Ir deprisa a pie", answers: ["CORRA","CORRAN","CORRAS","CORRE","CORREMOS","CORREN","CORRER","CORRES","CORRI","CORRIA","CORRIAN","CORRIDA","CORRIDO","CORRIERON","CORRIO","CORRISTE","CORRO"] },
  { id: "beber", clue: "Tragar un líquido", answers: ["BEBA","BEBAN","BEBAS","BEBE","BEBEMOS","BEBEN","BEBER","BEBES","BEBI","BEBIA","BEBIAN","BEBIDA","BEBIDO","BEBIERON","BEBIO","BEBISTE","BEBO"] },
  { id: "temer", clue: "Sentir miedo", answers: ["TEMA","TEMAN","TEMAS","TEME","TEMEMOS","TEMEN","TEMER","TEMES","TEMI","TEMIA","TEMIAN","TEMIDA","TEMIDO","TEMIERON","TEMIO","TEMISTE","TEMO"] },
  { id: "meter", clue: "Introducir algo dentro", answers: ["META","METAN","METAS","METE","METEMOS","METEN","METER","METES","METI","METIA","METIAN","METIDA","METIDO","METIERON","METIO","METISTE","METO"] },
  { id: "romper", clue: "Partir en pedazos", answers: ["ROMPA","ROMPAN","ROMPAS","ROMPE","ROMPEMOS","ROMPEN","ROMPER","ROMPES","ROMPI","ROMPIA","ROMPIAN","ROMPIDO","ROMPIERON","ROMPIO","ROMPISTE","ROMPO"] },
  { id: "barrer", clue: "Limpiar el suelo con escoba", answers: ["BARRA","BARRAN","BARRAS","BARRE","BARREMOS","BARREN","BARRER","BARRES","BARRI","BARRIA","BARRIAN","BARRIDA","BARRIDO","BARRIERON","BARRIO","BARRISTE","BARRO"] },
  { id: "vender", clue: "Dar algo a cambio de dinero", answers: ["VENDA","VENDAN","VENDAS","VENDE","VENDEMOS","VENDEN","VENDER","VENDES","VENDI","VENDIA","VENDIAN","VENDIDA","VENDIDO","VENDIERON","VENDIO","VENDISTE","VENDO"] },
  { id: "coser", clue: "Unir con hilo y aguja", answers: ["COSA","COSAN","COSAS","COSE","COSEMOS","COSEN","COSER","COSES","COSI","COSIA","COSIAN","COSIDA","COSIDO","COSIERON","COSIO","COSISTE","COSO"] },
  { id: "toser", clue: "Expulsar aire de los pulmones con ruido", answers: ["TOSA","TOSAN","TOSAS","TOSE","TOSEMOS","TOSEN","TOSER","TOSES","TOSI","TOSIA","TOSIAN","TOSIDA","TOSIDO","TOSIERON","TOSIO","TOSISTE","TOSO"] },
  { id: "subir", clue: "Ir hacia arriba", answers: ["SUBA","SUBAN","SUBAS","SUBE","SUBEN","SUBES","SUBI","SUBIA","SUBIAN","SUBIDA","SUBIDO","SUBIERON","SUBIMOS","SUBIO","SUBIR","SUBISTE","SUBO"] },
  { id: "vivir", clue: "Tener vida", answers: ["VIVA","VIVAN","VIVAS","VIVE","VIVEN","VIVES","VIVI","VIVIA","VIVIAN","VIVIDA","VIVIDO","VIVIERON","VIVIMOS","VIVIO","VIVIR","VIVISTE","VIVO"] },
  { id: "abrir", clue: "Descubrir lo que está cerrado", answers: ["ABRA","ABRAN","ABRAS","ABRE","ABREN","ABRES","ABRI","ABRIA","ABRIAN","ABRIERON","ABRIMOS","ABRIO","ABRIR","ABRISTE","ABRO"] },
  { id: "partir", clue: "Dividir o irse", answers: ["PARTA","PARTAN","PARTAS","PARTE","PARTEN","PARTES","PARTI","PARTIA","PARTIAN","PARTIDA","PARTIDO","PARTIERON","PARTIMOS","PARTIO","PARTIR","PARTISTE","PARTO"] },
  { id: "unir", clue: "Juntar dos cosas", answers: ["UNA","UNAN","UNAS","UNE","UNEN","UNES","UNI","UNIA","UNIAN","UNIDA","UNIDO","UNIERON","UNIMOS","UNIO","UNIR","UNISTE","UNO"] },
  { id: "sufrir", clue: "Padecer un dolor", answers: ["SUFRA","SUFRAN","SUFRAS","SUFRE","SUFREN","SUFRES","SUFRI","SUFRIA","SUFRIAN","SUFRIDA","SUFRIDO","SUFRIERON","SUFRIMOS","SUFRIO","SUFRIR","SUFRISTE","SUFRO"] },
  { id: "batir", clue: "Mover con fuerza una mezcla", answers: ["BATA","BATAN","BATAS","BATE","BATEN","BATES","BATI","BATIA","BATIAN","BATIDA","BATIDO","BATIERON","BATIMOS","BATIO","BATIR","BATISTE","BATO"] },
  { id: "latir", clue: "Dar golpes el corazón", answers: ["LATA","LATAN","LATAS","LATE","LATEN","LATES","LATI","LATIA","LATIAN","LATIDO","LATIERON","LATIMOS","LATIO","LATIR","LATISTE","LATO"] },
  { id: "pulir", clue: "Alisar y dar brillo", answers: ["PULA","PULAN","PULAS","PULE","PULEN","PULES","PULI","PULIA","PULIAN","PULIDA","PULIDO","PULIERON","PULIMOS","PULIO","PULIR","PULISTE","PULO"] },
  { id: "recibir", clue: "Tomar lo que llega", answers: ["RECIBA","RECIBAN","RECIBAS","RECIBE","RECIBEN","RECIBES","RECIBI","RECIBIA","RECIBIAN","RECIBIDA","RECIBIDO","RECIBIERON","RECIBIMOS","RECIBIO","RECIBIR","RECIBISTE","RECIBO"] },
  { id: "mar", clue: "Embarcación para navegar", answers: ["BALSA","BARCO","BOTE","BUQUE","CANOA","LANCHA","NAVE","REMO","VELA","YATE"] },
  { id: "dinero", clue: "Palabras para referirse al dinero", answers: ["BILLETE","FERIA","GUITA","LANA","LUCA","MOSCA","PASTA","PISTO","PLATA","VARO"] },
  { id: "nino", clue: "Persona de corta edad", answers: ["BEBE","CHAMACO","CHAVO","CHICO","CRIO","MORRO","NENE"] },
  { id: "perro", clue: "El mejor amigo del hombre", answers: ["CAN","CHUCHO","FIRULAIS","LOBO","PERRO"] },
  { id: "tonto", clue: "Insulto para alguien poco listo", answers: ["BOBO","BURRO","LELO","MENSO","NACO","PENDEJO","TONTO","ZONZO"] },
  { id: "casa", clue: "Lugar donde se habita", answers: ["CASA","CHOZA","CHOZO","HOGAR","NIDO"] },
  { id: "borracho", clue: "Que ha bebido de más", answers: ["BEODO","BOLO","EBRIO","PEDO"] },
  { id: "bonito", clue: "Que es agradable a la vista", answers: ["BELLO","CHULO","GUAPO","LINDO","MONO"] },
  { id: "comida", clue: "Alimentos para comer", answers: ["ARROZ","CALDO","CARNE","MOLE","PAN","QUESO","SOPA","TACO"] },
  { id: "miedo", clue: "Sensación de temor", answers: ["MIEDO","PANICO","PAVOR","SUSTO","TERROR"] },
];
